scalable_dir = 'hicolor' / 'scalable'
install_data(
  scalable_dir / 'apps' / ('page.codeberg.ostfriese4.Untis.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'apps'
)
install_data(
  scalable_dir / 'status' / ('starred-symbolic.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'status'
)
install_data(
  scalable_dir / 'status' / ('dialog-information-symbolic.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'status'
)
install_data(
  scalable_dir / 'legacy' / ('system-users-symbolic.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'status'
)
install_data(
  scalable_dir / 'status' / ('mail-unread-symbolic.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'status'
)
install_data(
  scalable_dir / 'status' / ('appointment-soon-symbolic.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'status'
)
install_data(
  scalable_dir / 'actions' / ('document-edit-symbolic.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'actions'
)
install_data(
  scalable_dir / 'ui' / ('checkbox-checked-symbolic.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'status'
)
install_data(
  scalable_dir / 'actions' / ('external-link-symbolic.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'actions'
)
install_data(
  scalable_dir / 'actions' / ('globe-alt-symbolic.svg'),
  install_dir: get_option('datadir') / 'icons' / scalable_dir / 'actions'
)